---
- name: Restart gophish
  ansible.builtin.systemd:
    name: gophish
    state: restarted
    daemon_reload: true

- name: Validate the nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  listen: Reload nginx

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  listen: Reload nginx
